/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

/**
 *
 * @author Cristopher M
 */
public class FRM_CrearReserva extends javax.swing.JFrame {

    /**
     * Creates new form FRM_CrearReserva
     */
    public FRM_CrearReserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        Lbl_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setBackground(new java.awt.Color(168, 205, 122));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setText("Indique el dueño de la reservación");
        jTextField2.setBorder(null);
        jTextField2.setCaretColor(new java.awt.Color(107, 170, 28));
        jTextField2.setSelectedTextColor(new java.awt.Color(107, 170, 28));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 230, 30));

        jTextField1.setBackground(new java.awt.Color(168, 205, 122));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("Indique el dueño de la reservación");
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(107, 170, 28));
        jTextField1.setSelectedTextColor(new java.awt.Color(107, 170, 28));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 170, 30));

        jTextField3.setBackground(new java.awt.Color(168, 205, 122));
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setText("Indique el dueño de la reservación");
        jTextField3.setBorder(null);
        jTextField3.setCaretColor(new java.awt.Color(107, 170, 28));
        jTextField3.setSelectedTextColor(new java.awt.Color(107, 170, 28));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 170, 30));

        jTextField4.setBackground(new java.awt.Color(168, 205, 122));
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        jTextField4.setText("Indique el dueño de la reservación");
        jTextField4.setBorder(null);
        jTextField4.setCaretColor(new java.awt.Color(107, 170, 28));
        jTextField4.setSelectedTextColor(new java.awt.Color(107, 170, 28));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 170, 30));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 240, 30));

        Lbl_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/frm_Reservacion.png"))); // NOI18N
        getContentPane().add(Lbl_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_Background;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
