/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Logica.Carrito.Reservacion;
import Logica.Carrito.nodoReservacion;
import Logica.Carrito.pilaReservacion;
import Logica.DB_Reservaciones;
import Logica.Usuario;
import Logica.colaReservacionesAnteriores;
import Logica.nodoColaAnteriores;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ExtremeTech
 */
public class FRM_ListaReservaciones extends javax.swing.JFrame {

    private pilaReservacion miPila;
    colaReservacionesAnteriores colaReservaciones = new colaReservacionesAnteriores();

    public FRM_ListaReservaciones() {
        initComponents();
    }

    public FRM_ListaReservaciones(pilaReservacion miPila) {
        initComponents();
        this.miPila = miPila;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Home = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_ListaReservaciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Home.setBackground(new java.awt.Color(107, 170, 28));
        btn_Home.setForeground(new java.awt.Color(107, 170, 28));
        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/btn_home.png"))); // NOI18N
        btn_Home.setBorder(null);
        btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));

        jT_ListaReservaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dueño de la reserva", "Cantidad de Personas", "Fecha y Hora", "Costo por Persona", "Costo total", "Costo IVA", "id_Usuario", "id_Reserva"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jT_ListaReservaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 930, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/frm_Generica.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 960, 607));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        //Crear nodos de la pila y de la cola en null al comienzo
        nodoReservacion miReserva = null;

        //Repetir el pop de la pila hasta que el devuelva nulo
        for (;;) {
            //Meter miReserva lo que se guardó en la pila
            miReserva = miPila.pop();

            //Meter en colaReservas lo que se guardó en la cola
            if (miReserva == null) {
                break;
            }
            //Sacar los datos de la pila y mostrarlos En la tabla

            //Creamos una varible de tipo tabla para agregar cosas.
            DefaultTableModel modelPersona = (DefaultTableModel) jT_ListaReservaciones.getModel();
            int id_Usuario = miReserva.getMiReservacion().getId_Usuario();
            int id_Reserva = miReserva.getMiReservacion().getId_Reserva();
            String nombreReservacion = miReserva.getMiReservacion().getNombreReservacion();
            int cantidadPersonas = miReserva.getMiReservacion().getCantidadPersonas();
            String fechaHora = miReserva.getMiReservacion().getFechaHora();
            float costoPersona = miReserva.getMiReservacion().getCostoPersona();
            float costoTotal = miReserva.getMiReservacion().getCostoTotal();
            float costoImpuestos = miReserva.getMiReservacion().getCostoImpuestos();

            //Guardar en la cola todos los datos de la pila.
            colaReservaciones.enCola(new nodoColaAnteriores(new Reservacion(id_Usuario, id_Reserva, nombreReservacion, cantidadPersonas, fechaHora, costoPersona, costoTotal, costoImpuestos)));

            //Agregar a la tabla los datos de la Pila
            modelPersona.addRow(new Object[]{nombreReservacion, cantidadPersonas, fechaHora, costoPersona, costoTotal, costoImpuestos, id_Usuario, id_Reserva});

        }

        //Llamar al metodo que está en la base de datos para guardar las reservaciones hechas
        //Si la cola vienen vacía es porque no hay ninguna reserva actualmente, por lo que no se manda a guardar nada.
        if (colaReservaciones != null) {
            DB_Reservaciones db_Reservaciones = new DB_Reservaciones();
            db_Reservaciones.crearReservacion(colaReservaciones);
        } else {
            JOptionPane.showMessageDialog(null, "No hay datos en la cola para mandar a guardar a la base de datos");
        }


    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomeActionPerformed

        this.dispose();
        FRM_AtraccionesCR atraccionesCR = new FRM_AtraccionesCR();
        atraccionesCR.setLocationRelativeTo(null);
        atraccionesCR.setVisible(true);
    }//GEN-LAST:event_btn_HomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_ListaReservaciones;
    // End of variables declaration//GEN-END:variables
}
