/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Logica.Carrito.Reservacion;
import Logica.Carrito.pilaReservacion;
import Logica.DB_Reservaciones;
import Logica.Usuario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ExtremeTech
 */
public class FRM_ConsultasReservaciones extends javax.swing.JFrame {

    private pilaReservacion miPila;
    private Usuario nuevoUsuario;

    public FRM_ConsultasReservaciones() {
        initComponents();
    }

    public FRM_ConsultasReservaciones(pilaReservacion miPila, Usuario nuevoUsuario) {
        initComponents();
        this.miPila = miPila;
        this.nuevoUsuario = nuevoUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn_Home = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_ListaReservaciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/Logo.png"))); // NOI18N
        jLabel2.setRequestFocusEnabled(false);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 80));

        btn_Home.setBackground(new java.awt.Color(107, 170, 28));
        btn_Home.setForeground(new java.awt.Color(107, 170, 28));
        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/btn_home.png"))); // NOI18N
        btn_Home.setBorder(null);
        btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));

        jT_ListaReservaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dueño de la reserva", "Cantidad de Personas", "Fecha y Hora", "Costo por Persona", "Costo total", "Costo IVA", "id_Reserva"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jT_ListaReservaciones);
        if (jT_ListaReservaciones.getColumnModel().getColumnCount() > 0) {
            jT_ListaReservaciones.getColumnModel().getColumn(6).setMinWidth(0);
            jT_ListaReservaciones.getColumnModel().getColumn(6).setPreferredWidth(0);
            jT_ListaReservaciones.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 930, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/frm_Generica.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 960, 607));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DB_Reservaciones db_Reservaciones = new DB_Reservaciones();
        ArrayList<Reservacion> extraerDatosAtracciones = db_Reservaciones.extraerDatosAtracciones();
        DefaultTableModel modelPersona = (DefaultTableModel) jT_ListaReservaciones.getModel();
        
        //Rellenar la tabla recursivamente
        cargarDatosRecursivamente(extraerDatosAtracciones,0,modelPersona);

    }//GEN-LAST:event_formWindowOpened

    private void cargarDatosRecursivamente(ArrayList<Reservacion> extraerDatosAtracciones, int indice, DefaultTableModel modelPersona) {
        if (indice < extraerDatosAtracciones.size()) {
            Reservacion miReserva = extraerDatosAtracciones.get(indice);

            String nombreReservacion = miReserva.getNombreReservacion();
            int cantidadPersonas = miReserva.getCantidadPersonas();
            String fechaHora = miReserva.getFechaHora();
            float costoPersona = miReserva.getCostoPersona();
            float costoTotal = miReserva.getCostoTotal();
            float costoImpuestos = miReserva.getCostoImpuestos();
            modelPersona.addRow(new Object[]{nombreReservacion, cantidadPersonas, fechaHora, costoPersona, costoTotal, costoImpuestos});
            cargarDatosRecursivamente(extraerDatosAtracciones, indice + 1, modelPersona);
        }
    }


    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomeActionPerformed

        this.dispose();
        FRM_AtraccionesCR atraccionesCR = new FRM_AtraccionesCR(miPila, nuevoUsuario);
        atraccionesCR.setLocationRelativeTo(null);
        atraccionesCR.setVisible(true);
    }//GEN-LAST:event_btn_HomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_ListaReservaciones;
    // End of variables declaration//GEN-END:variables
}
