/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

/**
 *
 * @author ExtremeTech
 */
public class FRM_CrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FRM_CrearUsuario
     */
    public FRM_CrearUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBConfirmar = new javax.swing.JButton();
        jTXT_ConfirmarContrasenna = new javax.swing.JTextField();
        jTXT_CorreoElectronico = new javax.swing.JTextField();
        jTXT_CrearUsuario = new javax.swing.JTextField();
        jTXT_Contrasenna = new javax.swing.JTextField();
        jLFondoCrearUsuario = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBConfirmar.setBackground(new java.awt.Color(255, 255, 255));
        jBConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/Botón Crear Usuario.png"))); // NOI18N
        jBConfirmar.setBorder(null);
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jBConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 150, 40));

        jTXT_ConfirmarContrasenna.setBackground(new java.awt.Color(168, 205, 122));
        jTXT_ConfirmarContrasenna.setBorder(null);
        getContentPane().add(jTXT_ConfirmarContrasenna, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 270, 30));

        jTXT_CorreoElectronico.setBackground(new java.awt.Color(168, 205, 122));
        jTXT_CorreoElectronico.setBorder(null);
        getContentPane().add(jTXT_CorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 270, 30));

        jTXT_CrearUsuario.setBackground(new java.awt.Color(168, 205, 122));
        jTXT_CrearUsuario.setBorder(null);
        getContentPane().add(jTXT_CrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 270, 30));

        jTXT_Contrasenna.setBackground(new java.awt.Color(168, 205, 122));
        jTXT_Contrasenna.setBorder(null);
        getContentPane().add(jTXT_Contrasenna, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 270, 30));

        jLFondoCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contents/frm_CrearUsuario.png"))); // NOI18N
        getContentPane().add(jLFondoCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -7, 950, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        FRM_Entrada frm_Entrada = new FRM_Entrada();
        this.dispose();
        frm_Entrada.setVisible(true);
    }//GEN-LAST:event_jBConfirmarActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JLabel jLFondoCrearUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTXT_ConfirmarContrasenna;
    private javax.swing.JTextField jTXT_Contrasenna;
    private javax.swing.JTextField jTXT_CorreoElectronico;
    private javax.swing.JTextField jTXT_CrearUsuario;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
