/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semana11_clienteservidor;

import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author ExtremeTech
 */
public class FRM_ChatCliente extends javax.swing.JFrame {

    /**
     * Creates new form FRM_ChatCliente
     */
    Cliente cliente;
    String ipDefault = "127.0.0.1";
    String puertoDefault = "10101";

    public FRM_ChatCliente() {
        initComponents();
        String vect[] = this.obtenerIPPuertoNombre();
        cliente = new Cliente(vect[2], vect[0], Integer.parseInt(vect[1]), this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSPanel = new javax.swing.JScrollPane();
        jTXTAChat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jCBDestinatario = new javax.swing.JComboBox<>();
        jTXTMensaje = new javax.swing.JTextField();
        jbtnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTXTAChat.setEditable(false);
        jTXTAChat.setColumns(20);
        jTXTAChat.setRows(5);
        jSPanel.setViewportView(jTXTAChat);

        jLabel1.setText("Destinatario: ");

        jbtnEnviar.setText("Enviar");
        jbtnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jCBDestinatario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTXTMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnEnviar)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jCBDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTXTMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEnviar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEnviarActionPerformed
        if (jCBDestinatario.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Error, debe seleccionar almenos 1 destinatario.");

        } else {
            String destinatario = jCBDestinatario.getSelectedItem().toString();
            String mensaje = jTXTMensaje.getText();
            cliente.enviarMensaje(destinatario, mensaje);
            jTXTAChat.append("**Yo--> " + destinatario + ":**\n" + mensaje + "\n");
            jTXTMensaje.setText("");

        }
    }//GEN-LAST:event_jbtnEnviarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cliente.solicitudDesconexion();
    }//GEN-LAST:event_formWindowClosing

    public void addUsuarios(String usuarioNuevo) {
        jCBDestinatario.addItem(usuarioNuevo);
    }

    public void dropUsuario(String usuario) {
        for (int i = 0; i < jCBDestinatario.getItemCount(); i++) {
            if (jCBDestinatario.getItemAt(i).toString().equals(usuario)) {
                jCBDestinatario.remove(i);
                return;

            }
        }
    }

    public void addmensaje(String usuario, String mensaje) {
        jTXTAChat.append("**" + usuario + "**\n" + mensaje + "\n");
    }

    private String[] obtenerIPPuertoNombre() {

        String[] vect = new String[3];

        //0. IP
        //1. Puerto
        //2. Nombre del chat
        vect[0] = ipDefault;
        vect[1] = puertoDefault;
        JTextField ip = new JTextField(20);
        JTextField puerto = new JTextField(20);
        JTextField usuario = new JTextField(20);
        ip.setText(ipDefault);
        puerto.setText(puertoDefault);
        usuario.setText("Usuario");

        JPanel jPanel = new JPanel();
        jPanel.setLayout(new GridLayout(3, 2));
        jPanel.add(new JLabel("Ip del server: "));
        jPanel.add(ip);
        jPanel.add(new JLabel("Puerto del Conexión: "));
        jPanel.add(puerto);
        jPanel.add(new JLabel("Nombre de Usuario "));
        jPanel.add(usuario);

        int resultado = JOptionPane.showConfirmDialog(null, jPanel, "Configuración", JOptionPane.OK_CANCEL_OPTION);

        if (resultado == JOptionPane.OK_OPTION) {
            vect[0] = ip.getText();
            vect[1] = puerto.getText();
            vect[2] = usuario.getText();
        } else {
            System.exit(0);
        }
        return vect;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBDestinatario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jSPanel;
    private javax.swing.JTextArea jTXTAChat;
    private javax.swing.JTextField jTXTMensaje;
    private javax.swing.JButton jbtnEnviar;
    // End of variables declaration//GEN-END:variables
}
